# Generated by Django 4.2 on 2023-04-21 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(max_length=100, verbose_name='Tipo de proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del proyecto')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='project_images', verbose_name='Imágen')),
                ('created', models.DateField(auto_now=True)),
                ('project_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projecttype')),
            ],
        ),
    ]
